<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userinfo.proto

namespace GPBMetadata;

class Userinfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a3e0a0e75736572696e666f2e70726f746f22240a0855736572496e666f" .
            "120a0a026964180120012805120c0a046e616d6518022001280962067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

