<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;事件联动消息结构体
 *
 * Generated from protobuf message <code>event.CommEventTrig</code>
 */
class CommEventTrig extends \Google\Protobuf\Internal\Message
{
    /**
     *联动类型: 参见联动类型定义blg.proto
     *
     * Generated from protobuf field <code>int32 trigger_type = 1;</code>
     */
    private $trigger_type = 0;
    /**
     *联动内容：参加联动格式定义blg.proto
     *
     * Generated from protobuf field <code>bytes trigger_info = 2;</code>
     */
    private $trigger_info = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $trigger_type
     *          联动类型: 参见联动类型定义blg.proto
     *     @type string $trigger_info
     *          联动内容：参加联动格式定义blg.proto
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Comm::initOnce();
        parent::__construct($data);
    }

    /**
     *联动类型: 参见联动类型定义blg.proto
     *
     * Generated from protobuf field <code>int32 trigger_type = 1;</code>
     * @return int
     */
    public function getTriggerType()
    {
        return $this->trigger_type;
    }

    /**
     *联动类型: 参见联动类型定义blg.proto
     *
     * Generated from protobuf field <code>int32 trigger_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTriggerType($var)
    {
        GPBUtil::checkInt32($var);
        $this->trigger_type = $var;

        return $this;
    }

    /**
     *联动内容：参加联动格式定义blg.proto
     *
     * Generated from protobuf field <code>bytes trigger_info = 2;</code>
     * @return string
     */
    public function getTriggerInfo()
    {
        return $this->trigger_info;
    }

    /**
     *联动内容：参加联动格式定义blg.proto
     *
     * Generated from protobuf field <code>bytes trigger_info = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTriggerInfo($var)
    {
        GPBUtil::checkString($var, False);
        $this->trigger_info = $var;

        return $this;
    }

}

