<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto

namespace Event;

/**
 *&#64;事件状态定义
 *
 * Protobuf type <code>event.EventState</code>
 */
class EventState
{
    /**
     *瞬时事件，保存
     *
     * Generated from protobuf enum <code>EVENT_STATE_INSTANT = 0;</code>
     */
    const EVENT_STATE_INSTANT = 0;
    /**
     *事件开始，保存
     *
     * Generated from protobuf enum <code>EVENT_STATE_START = 1;</code>
     */
    const EVENT_STATE_START = 1;
    /**
     *事件结束，更新结束时间
     *
     * Generated from protobuf enum <code>EVENT_STATE_STOP = 2;</code>
     */
    const EVENT_STATE_STOP = 2;
    /**
     *事件脉冲，客户端和服务器使用，CMS不用
     *
     * Generated from protobuf enum <code>EVENT_STATE_PULSE = 3;</code>
     */
    const EVENT_STATE_PULSE = 3;
    /**
     *事件更新，联动结果更新
     *
     * Generated from protobuf enum <code>EVENT_STATE_UPDATE = 4;</code>
     */
    const EVENT_STATE_UPDATE = 4;
}

