<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto

namespace Event;

/**
 *&#64;与事件分发服务通信的命令码定义
 *
 * Protobuf type <code>event.MsgCmdType</code>
 */
class MsgCmdType
{
    /**
     * Generated from protobuf enum <code>CZH_ADD_NO_USE = 0;</code>
     */
    const CZH_ADD_NO_USE = 0;
    /**
     *client msg 0x000001xxx
     *
     * Generated from protobuf enum <code>MSG_CMD_TYPE_MASK = 65280;</code>
     */
    const MSG_CMD_TYPE_MASK = 65280;
    /**
     *手动事件命令码
     *
     * Generated from protobuf enum <code>MSG_CMD_MANUAL_EVENT = 257;</code>
     */
    const MSG_CMD_MANUAL_EVENT = 257;
    /**
     *报警确认命令码
     *
     * Generated from protobuf enum <code>MSG_CMD_CONFIRM_EVENT = 258;</code>
     */
    const MSG_CMD_CONFIRM_EVENT = 258;
    /**
     *xx_2_eds msg 0x000002xxx
     *
     * Generated from protobuf enum <code>MSG_CMD_REPORT_EVENT = 513;</code>
     */
    const MSG_CMD_REPORT_EVENT = 513;
    /**
     *订阅事件命令码
     *
     * Generated from protobuf enum <code>MSG_CMD_SUBRECV_EVENT = 514;</code>
     */
    const MSG_CMD_SUBRECV_EVENT = 514;
    /**
     *eds_2_eds msg 0x000003xxx
     *
     * Generated from protobuf enum <code>MSG_CMD_EVENT_NOTIFY_REQ = 769;</code>
     */
    const MSG_CMD_EVENT_NOTIFY_REQ = 769;
    /**
     *事件分发服务内部事件通知响应
     *
     * Generated from protobuf enum <code>MSG_CMD_EVENT_NOTIFY_RSP = 770;</code>
     */
    const MSG_CMD_EVENT_NOTIFY_RSP = 770;
}

