<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;事件处理结果消息结构体
 *
 * Generated from protobuf message <code>event.TriggerResult</code>
 */
class TriggerResult extends \Google\Protobuf\Internal\Message
{
    /**
     *联动类型: 参见联动类型定义
     *
     * Generated from protobuf field <code>int32 trigger_type = 1;</code>
     */
    private $trigger_type = 0;
    /**
     *联动结果
     *
     * Generated from protobuf field <code>int32 trigger_ret = 2;</code>
     */
    private $trigger_ret = 0;
    /**
     *联动执行时间(确认时为确认时间)
     *
     * Generated from protobuf field <code>string trigger_time = 3;</code>
     */
    private $trigger_time = '';
    /**
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     *
     * Generated from protobuf field <code>string trigger_info = 33;</code>
     */
    private $trigger_info = '';
    /**
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     *
     * Generated from protobuf field <code>string err_msg = 34;</code>
     */
    private $err_msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $trigger_type
     *          联动类型: 参见联动类型定义
     *     @type int $trigger_ret
     *          联动结果
     *     @type string $trigger_time
     *          联动执行时间(确认时为确认时间)
     *     @type string $trigger_info
     *          联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     *     @type string $err_msg
     *          图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *          客户端确认信息:user_name;confirm_desc;user_ip;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Comm::initOnce();
        parent::__construct($data);
    }

    /**
     *联动类型: 参见联动类型定义
     *
     * Generated from protobuf field <code>int32 trigger_type = 1;</code>
     * @return int
     */
    public function getTriggerType()
    {
        return $this->trigger_type;
    }

    /**
     *联动类型: 参见联动类型定义
     *
     * Generated from protobuf field <code>int32 trigger_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTriggerType($var)
    {
        GPBUtil::checkInt32($var);
        $this->trigger_type = $var;

        return $this;
    }

    /**
     *联动结果
     *
     * Generated from protobuf field <code>int32 trigger_ret = 2;</code>
     * @return int
     */
    public function getTriggerRet()
    {
        return $this->trigger_ret;
    }

    /**
     *联动结果
     *
     * Generated from protobuf field <code>int32 trigger_ret = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTriggerRet($var)
    {
        GPBUtil::checkInt32($var);
        $this->trigger_ret = $var;

        return $this;
    }

    /**
     *联动执行时间(确认时为确认时间)
     *
     * Generated from protobuf field <code>string trigger_time = 3;</code>
     * @return string
     */
    public function getTriggerTime()
    {
        return $this->trigger_time;
    }

    /**
     *联动执行时间(确认时为确认时间)
     *
     * Generated from protobuf field <code>string trigger_time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTriggerTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->trigger_time = $var;

        return $this;
    }

    /**
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     *
     * Generated from protobuf field <code>string trigger_info = 33;</code>
     * @return string
     */
    public function getTriggerInfo()
    {
        return $this->trigger_info;
    }

    /**
     *联动详情，录像格式：监控点名称,录像计划Id,录像类型,监控点编号;
     *
     * Generated from protobuf field <code>string trigger_info = 33;</code>
     * @param string $var
     * @return $this
     */
    public function setTriggerInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->trigger_info = $var;

        return $this;
    }

    /**
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     *
     * Generated from protobuf field <code>string err_msg = 34;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->err_msg;
    }

    /**
     *图片联动 监控点名称,联动url,格式：cam1,url1;cam2,url2;
     *客户端确认信息:user_name;confirm_desc;user_ip;
     *
     * Generated from protobuf field <code>string err_msg = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->err_msg = $var;

        return $this;
    }

}

